
# Numeric Types:

# Integer
num_int = 10
# Float
num_float = 3.14
# Complex
num_complex = 2 + 3j

# Text type
# String
text_str = "Hello, world!"

# Sequence Type
# List
# Represents an ordered collection of items that can be of different data types.
# Lists are mutable, meaning their elements can be modified.
list_values = [1, 2, 3, 4, 5]
# Tuple
# Represents an ordered collection of items, similar to lists, but
# tuples are immutable, meaning their elements cannot be changed after creation.
tuple_values = (1, 2, 3, 4, 5)
# Range
# Represents a sequence of numbers generated by the range() function.
range_values = range(1, 6)  # Generates numbers from 1 to 5

# Mapping
# Dictionary : Represents a collection of key-value pairs.
# Keys are unique and immutable, while values can be of any data type.
dict_values = {'name': 'John', 'age': 30, 'city': 'New York'}

# Set Type
# Set represents an unordered collection of unique elements. Sets do not allow duplicate values.
set_values = {1, 2, 3, 4, 5}

# Frozen Set (frozenset): Similar to sets, but immutable,
# meaning elements cannot be added, removed, or modified after creation.
frozen_set_values = frozenset({1, 2, 3, 4, 5})


# Boolean Type:
# Boolean
bool_true = True
bool_false = False

# None Type
none_value = None
